spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb #;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  artemis:
    broker-url: artemis.tacocloud.com
    user: tacoweb
    password: l3tm31n
    embedded:
      enabled: false

messaging:
  queue:
    order:
      name: tacocloud.order.queue